extensions:
  client:
    endpoints:
      - wss://wss.api.moonriver.moonbeam.network:443
  event_bus:
  substrate_api:
    stale_timeout_seconds: 60
  cache:
    default_ttl_seconds: 0
    default_size: 2000
  merge_subscription:
    keep_alive_seconds: 60
  server:
    port: 9944
    listen_address: '0.0.0.0'
    max_connections: 2000

middlewares:
  methods:
    - response
    - inject_params
    - cache
    - upstream
  subscriptions:
    - merge_subscription
    - upstream

rpcs: substrate
